const intialConfig = {    
    m4 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m17 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p26 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m13 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p24 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p23 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m9 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m12b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p27b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m4b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p25b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m6b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p22 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m5 :{container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p30 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p31 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m14 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m12 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m1 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m16 : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p29b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m10b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m2b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p30b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m1p : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    p22b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0},
    m11b : {container: document.getElementById('schema'), 
            radius: 10,
            maxOpacity: 0.6, 
            minOpacity: 0}
}
export default intialConfig;